config/routes.rb
Rails.application.routes.draw do
  # get 'tasks_controller/new'
  # get 'tasks_controller/create'
  # get 'tasks_controller/update'
  # get 'tasks_controller/edit'
  # get 'tasks_controller/destroy'
  # get 'tasks_controller/index', to 'tasks#index'
  # # get 'tasks_controller/show'
  # get 'index', to: 'tasks#index'
  # get 'tasks/:id', to: 'tasks#show'
  # get 'tasks/new', to: 'tasks#new'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/:id/edit', to: 'tasks#edit'
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'

  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>TasksController#create</h1>
<p>Find me in app/views/tasks_controller/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>TasksController#destroy</h1>
<p>Find me in app/views/tasks_controller/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title, "Enter a task" %>
  <%= f.text_field :title %>
  <%= f.label :description, "Add some details" %>
  <%= f.text_field :details %>
  <% if @task.completed == true %>
  <%= f.label :completed, "The task is complete" %>
  <%= f.check_box :completed %>
  <% else %>
  <%= f.label :completed, "The task is incomplete" %>
  <%= f.check_box :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>To-do list </h1>

<div id="list-container">
  <table>
    <tbody>
      <% @tasks.each do |task| %>
          <tr>
            <% if task.completed == true %>
              <td><input type="checkbox" checked></td>
            <% else %>
              <td><input type="checkbox"></td>
            <% end %>
            <td><h2> <%= link_to(task.title, task_path(task)) %> </h2></td>
            <td><p><%= link_to "Delete Task", task_path(task), method: :delete %><p></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<% @task = Task.new %>
<%= form_for @task do |f| %>
  <%= f.label :title, "Enter a task" %>
  <%= f.text_field :title %>
  <%= f.label :description, "Add some details" %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Edit", edit_task_path %>
<%= link_to "Go back", tasks_path %>

app/views/tasks/update.html.erb
<h1>TasksController#update</h1>
<p>Find me in app/views/tasks_controller/update.html.erb</p>